# print ("========================")
# print ("student information")
# print ("Student ID :2024-001")
# print ("Name : Dara Sok ")
# print ("Gender : Male")
# print ("Level : year 1")
# print ("Grade : A")
# print ("========================")
# Student_id = input("enter student id:")
# Name = input("enter student name:")
# Gender = input("enter student gender:")
# Level = input("enter student level:")
# Grade = input("enter student grade:")

# print (f"student id : {Student_id}")
# print (f"student name : {Name}")
# print (f"student gender : {Gender}")
# print (f"student level : {Level}")
# print (f"student grade : {Grade}")

employee_id = input ("enter employee id : ")
employee_name = input ("enter your name : ")
hour = int(input ("enter your working hour : "))
rate = int(input ("enter you rate : "))
total_pay = hour*rate

print(f"employee id : {employee_id}")
print(f"employee name is : {employee_name}")
print(f"employee's working hour is : {hour}")
print(f"employee's wokring rate is : {rate}")
print (f"you total pay is : {total_pay}")